version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: djangorestproject-db
    restart: always
    environment:
      POSTGRES_DB: ${NAME}
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: djangorestproject-redis
    restart: always
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: djangorestproject-web
    restart: always
    env_file:
      - .env
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  celery:
    build: .
    container_name: djangorestproject-celery
    restart: always
    env_file:
      - .env
    command: celery -A courses worker -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  celery_beat:
    build: .
    container_name: djangorestproject-celery-beat
    restart: always
    env_file:
      - .env
    command: celery -A courses beat -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

volumes:
  postgres_data:

