# Generated by Django 6.0.2 on 2026-02-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='название курса')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='превью')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='название урока')),
                ('description', models.TextField(verbose_name='описание')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='превью')),
                ('link_video', models.TextField(verbose_name='ссылка на видео')),
            ],
        ),
    ]
