# Generated by Django 6.0.2 on 2026-02-10 11:29

import lms.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='link_video',
            field=models.TextField(validators=[lms.validators.validate_link], verbose_name='ссылка на видео'),
        ),
    ]
